### ISSUE TITLE
Grafana to filter terminated pods in Pods dashboard

### ISSUE THREAD

**Issue by heckdevice** [kubernetes/heapster#1179]
Does the influxdb schema support attribute to filter the Pods that are terminated in the Pods dashboard for Grafana?

I can filter the pods based on namespace but it lists all the pods (even the terminated ones)

Namespaces query  : SHOW TAG VALUES FROM "uptime" WITH KEY = "namespace_name"
Filtered Pod Query : SHOW TAG VALUES FROM "uptime" WITH KEY = "pod_name" WHERE pod_namespace =~ /$namespace/

influxdb : kubernetes/heapster_influxdb:v0.5
grafana : gcr.io/google_containers/heapster_grafana:v2.6.0-2
heapster : kubernetes/heapster:canary

**Comment by piosz** [comment]
There is no support for pod status in InfluxDB.

**Comment by ScubaDrew** [comment]
This is causing me a serious issue as users are forced to check dozens of terminated pods to find the/a active pod when you have pods that cycle frequently.

**Comment by heckdevice** [comment]
can be enhanced. .. is it feasible?

**Comment by fgrzadkowski** [comment]
One workaround could to show only those timeseries that have samples within the last X minutes. I'm not sure how expressive InfluxDB queries are though.

**Comment by shayderi** [comment]
Hi,
I also suffering from this problem,
My best solution was : add a variable that execute select query (call it livePods for instance):
select pod_name,value from uptime where time > now() - 20s

then you need to alter the query of  podname variable : 
show tag values from uptime with key = pod_name where "pod_name" =~ /$livePods$/

but the above solution is not satisfactory because grafana don't now how to deal with select query by displaying only pod_name (the result contains also time and value - the value is necessary for minimum one field is required in select query - from influx point of view)

any help for how to deal with the problem in other way will by appreciated 

Thanks
S.D

**Comment by sakthivel1988** [comment]
Hi

any update on this issue .

Regards,
Sakthi

**Comment by ShashankYadav** [comment]
For anyone who hits the issue, until there is a proper fix, you can use @shayderi's hack with a few tweaks in the template for livepods variable,which will give you all pods which were up in the last 2 minutes:

livepods : select pod_name,value from uptime where time > now() - 2m 
Filter : /.*-.*/

**Comment by sakthivel1988** [comment]
@ShashankYadav  its still not working for me .. can help me how to get that working

**Comment by nvartolomei** [comment]
No longer works with grafana 3.1.1 and influx 0.12 https://github.com/grafana/grafana/issues/5013

**Comment by neverfox** [comment]
Yeah, this is rough.

**Comment by discostur** [comment]
Any Update on this? Really annoying to klick through 50 Pods each time ...

**Comment by Crassirostris** [comment]
@discostur Sorry, I was slowed down by other things

I was thinking about making a template for amount of time, after which pod will be considered dead. What do you think about it?

**Comment by discostur** [comment]
@Crassirostris I think the best solution would be if you can tell Grafana to only show Pods for which are datapoints available (in relation to the given timeframe you have selected) but i'm not shure if this is possible.

In your solution, does it only work for a given time (like last 20 minutes) or can you adjust the timeframe by yourself? It would be really cool if you can set the scope for example to the last 6h oder last 24h and the "dead pods" are readjusting to that.

**Comment by Crassirostris** [comment]
@discostur Thanks for the feedback

> I think the best solution would be if you can tell Grafana to only show Pods for which are datapoints available

Makes sense, I will investigate whether it's possible.

> In your solution, does it only work for a given time (like last 20 minutes) or can you adjust the timeframe by yourself?

You can adjust.

**Comment by Crassirostris** [comment]
@discostur To give you an update. I was trying to set it up several times, but turns out grafana is very badly suited for this. You can only easily use tags from `SHOW TAG VALUES` query, which doesn't support filtering by time explicitly.

I tried to use SELECT to extract tag values, but it's certainly not designed to work out of the box. It may be possible after all, but it's not an easy task to bypass the design of grafana and its influx plugin. I will try to implement it in some way in the meantime, but can't promise anything, unfortunately.

**Comment by discostur** [comment]
@Crassirostris thanks for your update and your effort.

**Comment by Crassirostris** [comment]
@discostur There's a selector which results in needed information, but I still don't know how to make it work with Grafana template:

```
select pod_name, value from uptime where time > now() - 3m group by pod_name
```

**Comment by 0111sandesh** [comment]
Any update on this issue? I have been facing same issue with Grafana and InfluxDB for EC2 instances where certain instances go down and new instances take their place with different ip.

**Comment by Crassirostris** [comment]
@0111sandesh No, no progress was made so far, my last update still holds

**Comment by whereisaaron** [comment]
How about creating a [continuous query](https://docs.influxdata.com/influxdb/v1.2/query_language/continuous_queries/) in InfluxDB (using the 'select from uptime' query approach above) to keep track of the live pods, and then querying that derived measurement in Grafana?

**Comment by Crassirostris** [comment]
@whereisaaron Sounds promising, could you please make a PoC in the grafana interface? The main problem I had is selecting data from query to the template.

If it works, I will be happy to help you contribute that change or to do it for you!

**Comment by manuelschellenberg** [comment]
@whereisaaron any progress on that?

**Comment by whereisaaron** [comment]
Hi @manuelschellenberg yes I looked at it and the [influxdb query syntax](https://docs.influxdata.com/influxdb/v1.2/query_language/) and I fear it may be dead end. The problem is that the output of the [continuous query](https://docs.influxdata.com/influxdb/v1.2/query_language/continuous_queries/) must be another measurement. And that measurement has the same problem that queries must return at least one field.

I wondered if there is a way to query tags from one measurement into a string field on another measurement. The we could query just that field. However I can't see how that is possible with the available query syntax.

Plan B would be to create a '[templated query](http://docs.grafana.org/features/datasources/cloudwatch/#templated-queries)' for the Influxdb data source, similar to those used for the [CloudWatch data source](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.js#L231-L246). That way we could run the uptime query @heckdevice gives above and return just the tags as the result.

**Comment by Lebuin** [comment]
@whereisaaron @manuelschellenberg I'm a bit late to the party, but for anyone coming across this thread: I did manage to create a workaround using a continuous query. The following two influxdb commands create a new measurement `current_pods` that contains all the pods that were active somewhere in the last 2 hours. The `namespace_name`, `nodename` and `pod_name` tags are included. You can add other tags to the `GROUP BY` statement.

```
CREATE RETENTION POLICY "2hours" ON "k8s" DURATION 2h REPLICATION 1
CREATE CONTINUOUS QUERY current_pods_query ON k8s BEGIN SELECT max(value) AS value INTO k8s."2hours".current_pods FROM k8s."default".uptime WHERE type = 'pod' GROUP BY time(5m), namespace_name, nodename, pod_name END
```

**Comment by steve21168** [comment]
@Lebuin Thank you for your solution it helped me out.  

For anyone else not too familiar with influxDB like myself after following Lebuin's solution you want to update your template query to the following:
"SHOW TAG VALUES FROM k8s."2hours".current_pods WITH KEY = "pod_name" WHERE "namespace_name" =~ /$namespace$/"

**Comment by whereisaaron** [comment]
Thanks for the idea @Lebuin @steve21168 nice to have a workaround.

This remains a pain point for the grafana+influxdb combo, and certainly not a stale issue.

Luckily there may be some progress, with @daniellee picking up PR #7919 with a strategy to achieve it.

/lifecycle frozen

**Comment by shahbour** [comment]
I am totally new to grafana and influxDB so excuse me if it is so obvious question, but how can I create the two queries mentioned by @Lebuin
```
CREATE RETENTION POLICY "2hours" ON "k8s" DURATION 2h REPLICATION 1
CREATE CONTINUOUS QUERY current_pods_query ON k8s BEGIN SELECT max(value) AS value INTO k8s."2hours".current_pods FROM k8s."default".uptime WHERE type = 'pod' GROUP BY time(5m), namespace_name, nodename, pod_name END
```

Should I create them in Grafana or directly in influxDB

**Comment by Lebuin** [comment]
@shahbour Those 2 commands should be executed in InfluxDB itself, e.g. using the [cli](https://docs.influxdata.com/influxdb/v0.9/tools/shell/)
