### ISSUE TITLE
Error value for type node memory metrics 

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1248]
according to the [storage schema](https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md), all metrics info gathered from all k8s is about running pods and system containers. 

However, for node memory metrics, `memory/limit` and `memory/request` with type `node` are aggregated from all pods which is then aggregated from all containers running in pods. For more info please see [node_aggregator](https://github.com/kubernetes/heapster/blob/master/metrics/processors/node_aggregator.go#L31-L54) and [aggregator metrics definition](https://github.com/kubernetes/heapster/blob/master/metrics/heapster.go#L104-L163)

However, for other memory metrics with type node, such as 
* `memory/major_page_faults `
* `memory/major_page_faults_rate `
* `memory/page_faults `
* `memory/page_faults_rate`
* `memory/usage`
* `memory/working_set `

uses the value gained from [runc](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/memory.go) which is actually uses memory cgroups. currently, these memory metrics with type node uses the top level memory cgroup values from 
* `memory.stat.pgfault`
* `memory.stat.pgmajfault`
* `memory.usage_in_bytes`

This strategy is wrong, i think. we should aggregate these memory metrics just like `memory/limit` and `memory/request` with aggregating from all pods.

**More Info**:
according to [cgroups hierarchy spec](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) sec 5.2

```
# status considering hierarchy (see memory.use_hierarchy settings)
     
 hierarchical_memory_limit - # of bytes of memory limit with regard to hierarchy  
 			under which the memory cgroup is  
 hierarchical_memsw_limit - # of bytes of memory+swap limit with regard to  
 			hierarchy under which memory cgroup is.  
   
 total_<counter>		- # hierarchical version of <counter>, which in  
 			addition to the cgroup's own value includes the  
 			sum of all hierarchical children's values of  
 			<counter>, i.e. total_cache  
```

### **UPDATE**
----
The same as 
* `cpu/usage`
* `network/rx`
* `network/rx_rate`
* `network/rx_errors`
* `network/rx_errors_rate`
* `network/tx_errors`
* `network/rx_errors_rate`
* `network/tx`
* `network/tx_rate`
These metrics with type node will also need to aggregating value from all pods. :) 

If we want node level `cpu/usage` or `memory/usage` we should name them as `cpu/node_usage` or `memory/node_usage`

**Comment by piosz** [comment]
This is working as intended. First it doesn't make sense to do aggregation from cumulative metrics, because usually containers have different start times. Second we are collecting metrics also for system containers: kubelet, kube-proxy, system and docker, so if we make an aggregation from all containers running on the node at least in theory this should be equal to what is collected for the node itself. In practice since we sometimes metrics for a container will be missed and cadvisor collects them at different times the current method will be more accurate.

Requests and limits are aggregated from running pods because it's not defined for a node itself. It's a legacy functionality required by previous implementation of [cluster autoscaler](https://github.com/kubernetes/heapster/blob/master/metrics/processors/node_autoscaling_enricher.go).

Thanks for your help. Sorry, that I haven't responded faster but I somehow missed it.
