### ISSUE TITLE
Add a prometheus sink (possibly via the pushgateway)

### ISSUE THREAD

**Issue by zilman** [kubernetes/heapster#1302]
Since Heapster began supporting the Influxdb/grafana pairing, grafana has added Prometheus as a data source and its getting to the point where one can pretty reliably swap data stores. This is desirable for a fair and possibly growing amount of users.

There's a difference in operating models of course with the push vs pull thing. One possible way to get around it is to add support for the [Prometheus Pushgateway](https://github.com/prometheus/pushgateway) as a Heapster sink.

A better way would probably be to allow Heapster to be scraped by Prometheus. This doesn't necessarily even have to be done in the Heapster codebase, one could write an exporter to run along side -- however I am weary of doing so as the Heapster API is not yet stable so I'm opening this discussion.

Please advise.

**Comment by piosz** [comment]
We are working on overall monitoring vision in Kubernetes, which should be discussed on [sig-instrumentation](https://github.com/kubernetes/community/blob/master/sig-instrumentation/README.md) meetings soon. If you are interested feel invited. In the meantime I'm closing the issue, because it's about the architecture of monitoring pipeline in general.

cc @fgrzadkowski @fabxc
