### ISSUE TITLE
ElasticSearch | time-based index

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes/heapster#1310]
We need to make heapster report the data into a time-based index, which will allow easy management of the database(and removing old indexes)

https://www.elastic.co/guide/en/elasticsearch/guide/current/time-based.html

**Comment by commixon** [comment]
+1. I think this is important as well. 
Maybe something simple like:
```
        if indexName == "" || typeName == "" || sinkData == nil {
                return nil
        }
+       // Index in format indexName-yyyy-mm-dd
+       indexName += "-" + time.Now().Format("2006-01-02")
+
```

Or this could be done by a flag in options (e.g. ?timestampFormat=true).

I could find some time to work on this, but as I am by no means a go expert maybe someone else is better suited and willing to take the task?

**Comment by AlmogBaku** [comment]
Hi,
I have solved that in PR #1313 
Waiting for someone to review it for almost a month...

@commixon it'll be very helpful if you'll help us reviewing :D

**Comment by commixon** [comment]
Will do asap! From a first look the only thing that seems to be "difficult" to digest is that this PR brings breaking changes. BUT, they are most welcome since they are optimized for ElasticSearch. All of the changes introduced are valid in my opinion.

(I am the second one trying to create dashboards from the previous schema :) )

Don't know however how can we speed up the reviewing process. 

Will try to build images from your branch and deploy them in testing to see how everything works.

**Comment by piosz** [comment]
@commixon could you please take a look into #1313
