### ISSUE TITLE
Please publish heapster binary

### ISSUE THREAD

**Issue by mingfang** [kubernetes/heapster#1395]
Currently most of the Kubernetes binaries are published for download here https://storage.googleapis.com/kubernetes-release/.

Please also add the heapster binary.

**Comment by andyxning** [comment]
@piosz This is convenient for end users. I have no idea about whether there is a tool can help us  adding mac OSX and Linux binary release easily when releasing.

**Comment by DirectXMan12** [comment]
@piosz what needs to be done to get these posted?  Who has access?

**Comment by piosz** [comment]
How about doing it in https://github.com/kubernetes/heapster/releases? Is this sufficient solution?

**Comment by mingfang** [comment]
Yes! Please.

**Comment by piosz** [comment]
@luxas

**Comment by luxas** [comment]
Yes, and for all architectures :)

That's just a matter of uploading binaries to Github, so that's easy

**Comment by mingfang** [comment]
Any chance this can be done for the new release, v1.3.0?

**Comment by mingfang** [comment]
This is not strictly necessary anymore since now I can do this in a Dockerfile
```COPY --from=gcr.io/google_containers/heapster:v1.4.1 heapster /heapster/heapster```

Feel free to close this.

**Comment by kadamvandita** [comment]
How to copy obtain the binary other then then in dockerfile?

**Comment by andyxning** [comment]
@kadamvandita you can simply compile heapster and eventer by `make build` under top level dir.

**Comment by kadamvandita** [comment]
yes.. I tried it.But when I write a spec file for it and run it I get warning saying unstripped binary for s390x .Any idea on this?

**Comment by andyxning** [comment]
@kadamvandita 

> a spec file

what is a spec file? Could you please paste it here?

> I get warning saying unstripped binary for s390x.

what is your compile machine's arch and os.

**Comment by kadamvandita** [comment]
spec file is a file written to generate rpm .Its for s390x SUSE architecture

#
# spec file for package heapster
#
# Copyright (c) 2017 SUSE LINUX Products GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#

Name:           heapster
Version:        1.4.1
Release:        1
License:        Apache-2.0
Summary:        Enables Container Cluster Monitoring and Performance Analysis
Url:            https://github.com/kubernetes/heapster
Group:          Applications/Productivity
Source:         https://github.com/kubernetes/heapster/archive/v1.4.1.tar.gz
Source1:        https://github.com/tools/godep/archive/v79.tar.gz
BuildRequires:   git make wget gcc tar go rpm gcc gcc-c++ libseccomp-devel flex  binutils-devel gmp-devel mpfr-devel mpc-devel ruby docker
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
ExclusiveArch:  s390x

%description
Heapster collects and interprets various signals like compute resource usage, lifecycle events, etc, and exports cluster metrics via REST endpoints.Heapster supports the pluggable storage backends.

%global debug_package %{nil}
%global __os_install_post %{nil}
%prep
%setup -q -n heapster-%{version}
%setup -n heapster-%{version} -T -D -b 1

%build
Platform=s390x
MAINROOT=`pwd`
cd ..
export GOPATH=`pwd`
export PATH=$PATH:$GOPATH/bin:$HOME/go/bin

docker copy --from=gcr.io/google_containers/heapster-s390x:v1.4.1 heapster /heapster/heapster
mkdir -p $GOPATH/src/github.com/tools/godep
cd $GOPATH/src/github.com/tools/godep
cp -R $GOPATH/godep-79/* .
go install -x
cd -

mkdir -p $GOPATH/src/k8s.io/heapster
cp -R heapster-%{version}/* $GOPATH/src/k8s.io/heapster
cd $GOPATH/src/k8s.io/heapster
make ARCH=$Platform
chmod 0755 %{_builddir}/src/k8s.io/heapster/heapster

%install
mkdir -p $RPM_BUILD_ROOT/usr/bin
cp %{_builddir}/src/k8s.io/heapster/heapster $RPM_BUILD_ROOT/usr/bin/


%files
%defattr(-,root,root)
%{_bindir}/heapster
%doc  LICENSE CONTRIBUTING.md

%changelog

**Comment by kadamvandita** [comment]
I needed the binary so that I can include directly in the spec file
