### ISSUE TITLE
Any plans to support Elasticsearch 5

### ISSUE THREAD

**Issue by maxott** [kubernetes/heapster#1410]
It appears that 1.2 can't connect to ES5

```E1212 05:24:11.987800     120 factory.go:75] Failed to create sink: Failed to create ElasticSearch client: no Elasticsearch node available```

It works perfectly fine for ES2. Unfortunately, some of my other components require ES5.

Any current plans to upgrade the ES backend?

**Comment by AlmogBaku** [comment]
Upgrading to ES5 will break the current support of ES2...
I think that  for the time being we need to support both of the sinks version..

Also, It looks like we'll have to replace only the ES driver and not the eventer/heapster sinks, since it's modular.

Currently I don't have the time/resources to build the ansible script to install ES5, so I'll have to wait for ES team to update the script in order to create a new ES Cluster..

**Comment by rikatz** [comment]
@AlmogBaku Why it will break support to ES2? I think it's only something like pointing the lib contained here: https://github.com/kubernetes/heapster/blob/master/common/elasticsearch/elasticsearch.go#L25

To the v5 library, right?

I'll try to change the source code pointing to this new version, and see what happens. We did this earlier with telegraf and worked fine, the only real problem was with fields containing '.' character, because ES 2 does not support them.

**Comment by rikatz** [comment]
Guys, it's pretty simple to support Elastic v5. I did some simple tests here and it worked. I'm going to open a PR late tomorrow, to change the lib version (and some minor changes needed to make this work) and post here.

**Comment by AlmogBaku** [comment]
https://github.com/olivere/elastic/issues/431

**Comment by AlmogBaku** [comment]
@rikatz the discussion on the issue above means that we need to create a different sink for es5; however all the drivers can be the same

**Comment by rikatz** [comment]
@maxott Elasticsearch 5 is already supported in Heapster (as merged in #1607).

Can you please close this issue?

Thanks!
