### ISSUE TITLE
The 'phantomjs' binary in the grafana 4.0.2 image won't run

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes/heapster#1494]
Using the `gcr.io/google_containers/heapster-grafana-amd64:v4.0.2` image there appears to be a problem with the `phantomjs` binary. The binary ships with grafana and is in the image but doesn't run with a 'not found' error. Perhaps a linking issue and a dependency is missing?

I get errors like these in the grafana log.
```
t=2017-01-31T02:05:30+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="fork/exec /usr/share/grafana/vendor/phantomjs/phantomjs: no such file or directory"
```

Checking the container the binary is actually there, but won't execute.
```
~ # ls -l /usr/share/grafana/vendor/phantomjs/
total 66352
-rwxr-xr-x    4 root     root      67932064 Dec  8 13:28 phantomjs
-rw-r--r--    4 root     root          2213 Dec  8 13:26 render.js
~ # /usr/share/grafana/vendor/phantomjs/phantomjs 
sh: /usr/share/grafana/vendor/phantomjs/phantomjs: not found
```

According to the [upstream for phantomjs](http://phantomjs.org/download.html) the binaries are static, but does require `fontconfig` which I guess the base 'busybox' image is not providing.

> Note: For this static build, the binary is self-contained. There is no requirement to install Qt, WebKit, or any other libraries. It however still relies on Fontconfig (the package fontconfig or libfontconfig, depending on the distribution). The system must have GLIBCXX_3.4.9 and GLIBC_2.7.

The [official container build](https://github.com/grafana/grafana-docker/blob/master/Dockerfile) is based on debian:jessie and install `libfontconfig` so that may be the difference.

**Comment by KarolKraskiewicz** [comment]
It seems the error occurs when trying to export a graph in graphana as an image. I also agree it appears that missing `fontconfig` is the root cause.

I tried to add `fontconfig` to busybox, but since busybox does not have any package manager, and `fontconfig` have some dependencies, it is not very practical.

An alternative would be to change the container form busybox to something with a package manager, for example [apline](https://hub.docker.com/_/alpine/), but it would be a bigger change, and I'm wondering if it is worth it just to provide the "snapshot to image" capability in grafana.

@piosz any thoughts?

**Comment by whereisaaron** [comment]
Thanks @KarolKraskiewicz, I dealt with this problem (and other problems) by switching to the [official Grafana Docker image](https://hub.docker.com/r/grafana/grafana/) which is [based on `debian:jessie`](https://github.com/grafana/grafana-docker/blob/master/Dockerfile). I also made a [couple of tweaks](https://hub.docker.com/r/whereisaaron/grafana-kubernetes/) to better suit Kubernetes. This has the side-benefit of upgrading to grafana the current 4.2.0 version.

The busybox container caused other problems for me too, e.g. it lacked a root cert collection and so couldn't send email alerts or generate Slack notifications. Alpine could work, but sticking with the tested upstream build seems a better way to go. Certainly it is working well for me with combined with the heapster and influxdb from the project.

**Comment by piosz** [comment]
We can use a different image. @timstclair what is the recommended base image with package manager?

**Comment by diseku** [comment]
Any update on it? Using the image version 4.4.1, same issue:

`t=2017-08-07T13:08:30+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="fork/exec /usr/share/grafana/vendor/phantomjs/phantomjs: no such file or directory"`

**Comment by gimlet2** [comment]
Guys, any plan to fix it somewhere soon?

**Comment by gdulus** [comment]
+1

**Comment by royeectu** [comment]
+1

**Comment by aharonh** [comment]
+1

**Comment by DirectXMan12** [comment]
*please* stop `+1`-ing.  It doesn't help the situation.  If you *really* feel the need to `+1`, use the reaction button.

@piosz @kawych @loburm @x13n I think we need to switch the base image.  I suspect `alpine` is probably fine, since it doesn't look like there are any other recommendations...

Everyone else: in the mean time, I'd recommend building your own image if you care about this functionality.
