### ISSUE TITLE
[Hawkular Sink] The namespace metrics should go under the project tenant

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#1531]
Currently the namespace metrics are ending up in the _system tenant. These should be stored in each individual project's tenant instead.

**Comment by mwringe** [comment]
@burmanm can you take a look if you have the chance?

**Comment by burmanm** [comment]
So, the reason is that we still use in the origin-metrics the pod_namespace label, which isn't stored when Heapster stores the namespace-level metrics:

https://github.com/kubernetes/heapster/blob/96d9dbf9ee20c200bb7703a8dff0b5ea7c1d1ba1/metrics/processors/namespace_aggregator.go#L60

And for that reason, the matching fails.

**Comment by burmanm** [comment]
Fixed here instead: https://github.com/openshift/origin-metrics/pull/319
