### ISSUE TITLE
memory/usage of cluster differs from sum of all nodes

### ISSUE THREAD

**Issue by derbeneviv** [kubernetes/heapster#1593]
Hello!
we are using kubernetes v1.3.0+52492b4 (openshift) and heapster: v1.3.0-beta.0

that's what we noticed:
memory/usage for a cluster greatly differs from the one for a sum of nodes
like (query from influx):
```
select (value) from "memory/usage" WHERE "type" = 'cluster' and time > now() - 1m and time < now()
```
returns 	_75078987776_
and 
```
select sum(value) from "memory/usage" WHERE "type" = 'node' and time > now() -  1m and time < now()
```
returns _39981445120_

so, the question is  - is that a bug, or heapster\kubernetes caculates memoty usage of the whole cluster as something different from the sum of memory usage of all nodes?

**Comment by DirectXMan12** [comment]
IIRC, there was, at one point, some issues double-counting things at the node and cluster levels.  That should be fixed in master, I believe.

A heads up though -- you might have some issues running Heapster 1.3.0 against Kubernetes 1.3.0 -- the Heapster versioning doesn't match up with Kubernetes versioning, so Heapster 1.3.0 is quite newer than Kubernetes 1.3.0.  Heapster 1.3.0 is designed to work with Kubernetes 1.5 and Kubernetes 1.6.

**Comment by DirectXMan12** [comment]
(I'm closing this now, but feel free to re-open if you have further questions or if the latest Heapster does not solve your issue)

**Comment by derbeneviv** [comment]
@DirectXMan12 should i re-create an issue or you can re-open it?

what i tried:
1) built and pushed current master branch - i got the same problem as here https://github.com/kubernetes/heapster/issues/1583 
2) pushed v1.2.0-2 from here: https://hub.docker.com/r/openshift/origin-metrics-heapster-base/tags/ ( that should be the correct version, i imagine)

result (for 1.2.0, it doesn't differ from 1.3.0-beta really):
```
[root@development33-node-6 ~]# free -m
 total        used        free      shared  buff/cache   available
Mem:          32012        5558       12293        1767       14159       24024
```
so memory/used whould be smth like 19 gig, right?
but it shows 18:
```
select value/1024/1024 from "memory/usage" where  nodename='development33-node-6'  and type = 'node' and time > now() - 70s 
>17944.68359375
```
sum(value) of type='pod' for a single host seems to be right, it equals stats which i got from docker(sum of total memory usage of all containers), but it differs from type = 'node':
11435.2109375Mib(all pods) vs 17944.68359375Mib(node)

same for cluster again:
```
select sum(value)/1024/1024 from "memory/usage" where   type ='node' and time > now() - 70s
>302423.734375
select value/1024/1024 from "memory/usage" where   type ='cluster' and time > now() - 70s
>589107.94140625
```
How does heapster collect its metrics? Especially for node and cluster level, pods seems to be ok.
Is there a way to run all its api calls manually? Maybe we have smth wrong with our kubernetes installation?

**Comment by derbeneviv** [comment]
@DirectXMan12 you also mentioned some issues double-counting things at the node and cluster levels. 
Can you point it please, i couldn't find it.
Maybe i can build an image from exact commit

**Comment by DirectXMan12** [comment]
> How does heapster collect its metrics? Especially for node and cluster level, pods seems to be ok.

So, it looks like for the node, we get the memory/usage value directly from Kubelet/cAdvisor -- that's not one of the ones that we aggregate up from pods.  So whatever you're seeing, that's what Kubelet is telling us.

> Is there a way to run all its api calls manually?

When configured to use the summary endpoint (the recommended way -- `--source=kubernetes.summary_api`), Heapster will hit the summary endpoint of each node using a GET.  That's served at `http://$NODE_IP:10255/stats/summary`.  Otherwise, it will repeatedly hit each of the stats endpoints, which is a bit more difficult to replicate yourself.  It's probably easiest to start looking at the data provided by the summary endpoint and check that it matches what you'd expect.

> you also mentioned some issues double-counting things at the node and cluster levels

Specifically, at the cluster level, there was an issue at one point involving double-counting due to the way cAdvisor interprets what a "system container" is (a collection of cgroups), and the fact that the cluster-level metrics include system containers.  I would recommend against trusting the numbers produced as "cluster level" numbers.  The node-level ones should be fine, though

**Comment by darkprisco** [comment]
Sorry but I didn't get, I mean I am facing similar problem on my kubernetes cluster.
kubectl top showing something different than kubectl describe and more over, if I kubectl top pods and I sum all memory used by pods running on the same agent I don't match value showed by kubectl top nodes.

**Comment by DirectXMan12** [comment]
Note that the sum of all pods is not necessarily the memory usage on the node.  The sum of all pods should be at most the memory usage of the node, but the node should have other processes that are using memory on it as well.

**Comment by chengwang86** [comment]
@DirectXMan12 Hi I still observe that the sum of all worker nodes' memory usage > cluster mem usage. See https://github.com/kubernetes/heapster/issues/1897. I tried with heapster 1.3.0 and 1.4.2, the kubernetes version is 1.8.2
