### ISSUE TITLE
Have ElasticSearch sink only emit events

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/heapster#1706]
We already use prometheus for metrics, and would like to send only events to ElasticSearch it would be great if this were configurable.

**Comment by piosz** [comment]
ElasticSeach is supported in eventer, so you can setup it. Instead of `heapster` you need to run `eventer`, see for example `eventer` container which exports events to InfluxDB [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml#L61). Feel free to ping me on slack. Also I'm happy to accept your contribution to the documentation once you figure out how to do it:)
