### ISSUE TITLE
Clarification regarging pod level aggregation for Cpu/usage 

### ISSUE THREAD

**Issue by Gianman** [kubernetes/heapster#1751]
Hello,

It appears that there is an issue when [aggregating ](https://github.com/kubernetes/heapster/blob/master/metrics/processors/pod_aggregator.go#L117) pod level metrics that are not of type `MetricGauge`. They seem to be completely skipped. Is this the expected behavior?

Furthermore, I was wondering how to efficiently and accurately calculate pod level aggregation for **[cpu/usage](https://github.com/kubernetes/heapster/blob/master/metrics/core/metrics.go#L182)** metric. More specifically, assuming there is a pod with N containers running inside it, I would like to efficiently calculate:
 `pod_cpu_usage = cont1_cpu_usage + cont2_cpu_usage + ... + contN_cpu_usage` , for each period.
 
Thank you very much in advance.

**Comment by DirectXMan12** [comment]
@piosz do you remember why we don't aggregate cumulative metrics together?

**Comment by Gianman** [comment]
Hello,

Any update/clarification regarding this issue?

Thanks in advance.

**Comment by kinsu** [comment]
from the pod_aggregator it appears that this was done on purpose
https://github.com/kubernetes/heapster/blob/master/metrics/processors/pod_aggregator.go#L119

but this (at least to me) is kind-of contradictory since heapster is suppose to aggregate the data in pod level.

some insight on this would be great!

**Comment by DirectXMan12** [comment]
honestly, I'm not sure.  It's possible that it was just to save space in-memory, because mostly we only care about rate metrics.

**Comment by kinsu** [comment]
we tried to change/remove this constrain (i.e. the check for non-cummulative type of metric in pod_aggregator.go) but faced a strange outcome. 
That is, negative values were visible in usage_rate. 

from what I can see, in case we have 1 container within the pod (+ pause container) 
```
pod_aggregator_values#   MetricName:  cpu/usage     Podname:  test-server    OldAggrValueBefore:  159812027  NewMetricValue:  24757079714362 NewAggregatedValue 24757239526389

rate_calculator#    Pod:  dummypod    metricValNew:  159954312  metricValOld:  24757239526389    NewVal:  -691752
rate_calculator#    Pod:  dummypod    metricValNew:  24765917979065  metricValOld:  24757079714362    NewVal:  311
```

But also if more than one container exists (apart from the pause container) in the same pod:
```
rate_calculator#    Pod:  test-server    metricValNew:  20120578914  metricValOld:  20113753416    NewVal:  0
rate_calculator#    Pod:  test-server    metricValNew:  19645284455  metricValOld:  19638330290    NewVal:  0
rate_calculator#    Pod:  test-server    metricValNew:  142284977  metricValOld:  514349464276    NewVal:  -16050
rate_calculator#    Pod:  test-server    metricValNew:  335822999773  metricValOld:  335774391520    NewVal:  2
rate_calculator#    Pod:  test-server    metricValNew:  20562033995  metricValOld:  20555225125    NewVal:  0
rate_calculator#    Pod:  test-server    metricValNew:  41405300433  metricValOld:  41392672637    NewVal:  0
rate_calculator#    Pod:  test-server    metricValNew:  15943527234  metricValOld:  15939907389    NewVal:  0
rate_calculator#    Pod:  test-server    metricValNew:  60800262779  metricValOld:  60792898922    NewVal:  0
```
where the -16050 coming from the subtraction of the current value (142284977) minus this 335774391520 which actually is the aggregated value that produced from the previous (!) run (previous sampling) of the pod_aggregator processor. 
```
pod_aggregator_values#   MetricName:  cpu/usage     Podname:  test-server     OldAggrValueBefore:  498409556887  NewMetricValue:  15939907389 NewAggregatedValue 514349464276

the negative value _always_ comes from _pause_ container
    "app": "myapplication",
    "io.kubernetes.container.name": "POD",
    "io.kubernetes.docker.type": "podsandbox",
    "io.kubernetes.pod.name": "dummypod",
    "io.kubernetes.pod.namespace": "default",
```
If we skip the POD types in rate calculator then the pod aggregated values as well as the values for the pod_containers for cpu usage & cpu usage_rate are OK! (even when pod contains more than one container).

the aggregated values are stored in the metricset with a key derived from the ns,podname, while in RateCalculator the "for loop" is using a key that is again derived from ns,podname and the key for the pause container appears to be _exactly_ the same as the key for the pod level statistics.

*Question* is: 
Even though the pause container is type "pod" shouldn't heapster mark it differently i.e. following the pattern for containers (namespace:%s/pod:%s/container:%s ) or whatever, 
in order to avoid confusion with pod level aggregated values ?

**Comment by kinsu** [comment]
my point was to treat the pause container as other containers. That is:

```
diff --git a/metrics/sources/kubelet/kubelet.go b/metrics/sources/kubelet/kubelet.go
index f2d78d0..23f6a2e 100644
--- a/metrics/sources/kubelet/kubelet.go
+++ b/metrics/sources/kubelet/kubelet.go
@@ -98,15 +98,16 @@ func (this *kubeletMetricsSource) handleSystemContainer(c *cadvisor.ContainerInf
 
 func (this *kubeletMetricsSource) handleKubernetesContainer(cName, ns, podName string, c *cadvisor.ContainerInfo, cMetrics *MetricSet) string {
        var metricSetKey string
-       if cName == infraContainerName {
-               metricSetKey = PodKey(ns, podName)
-               cMetrics.Labels[LabelMetricSetType.Key] = MetricSetTypePod
-       } else {
-               metricSetKey = PodContainerKey(ns, podName, cName)
-               cMetrics.Labels[LabelMetricSetType.Key] = MetricSetTypePodContainer
-               cMetrics.Labels[LabelContainerName.Key] = cName
-               cMetrics.Labels[LabelContainerBaseImage.Key] = c.Spec.Image
-       }
+       // if cName == infraContainerName {
+       //      fmt.Println("kubelet#    podName:", podName, "    cName:", cName)
+       //      metricSetKey = PodKey(ns, podName)
+       //      cMetrics.Labels[LabelMetricSetType.Key] = MetricSetTypePod
+       // } else {
+       metricSetKey = PodContainerKey(ns, podName, cName)
+       cMetrics.Labels[LabelMetricSetType.Key] = MetricSetTypePodContainer
+       cMetrics.Labels[LabelContainerName.Key] = cName
+       cMetrics.Labels[LabelContainerBaseImage.Key] = c.Spec.Image
+       //}
        cMetrics.Labels[LabelPodId.Key] = c.Spec.Labels[kubernetesPodUID]
        cMetrics.Labels[LabelPodName.Key] = podName
        cMetrics.Labels[LabelNamespaceName.Key] = ns
```
Using the above, pod levels cummulative counters are working now (correctly aggregated).

Do you see any problem with the above approach ?

thank you in advance!

**Comment by DirectXMan12** [comment]
I'm tempted to close this as I'm not particularly keen on adding new features to Heapster and/or increasing the memory bloat (which is already fairly large).  If you have a compelling use case and are still interested, please share.
