### ISSUE TITLE
Heapster API: listing metric names doesn't show filesystem metrics.

### ISSUE THREAD

**Issue by verult** [kubernetes/heapster#1877]
Steps to reproduce:

1) `curl <heapster_host:port>/api/v1/model/namespaces/{namespace-name}/pods/{pod-name}/metrics/`

What to expect:
Filesystem metrics should be listed

What happens:
Filesystem metrics missing

This happens at all levels, not just pod metrics. Is this intentional?

The problem is here:
https://github.com/kubernetes/heapster/blob/master/metrics/sinks/metric/metric_sink.go#L223
Filesystem metrics are stored in MetricSet.LabeledMetrics, which GetMetricNames doesn't look through.

**Comment by DirectXMan12** [comment]
The model API never left alpha, and is deprecated (I need to put a large warning on the Heapster README).  It's typically because labeled metrics don't show up as normal in the model API.  If they're not showing up in you sink, that would be a problem, but it's more-or-less expected in the model API, and we have no plans to improve that.

**Comment by RobbieXie** [comment]
I got the same issue, filesystem and disk metircs are missing while others seems good. 
Anyone has an solution to get filesystem & disk metrics through heapster?
