### ISSUE TITLE
We need an official Influx sink owner

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/heapster#1945]
The influxdb sink issues are getting a bit out of hand.  We need an official Influx sink owner beyond just @kubernetes/heapster-maintainers, IMO.

There are currently 17 open bugs with sink/influxdb label and 34 open bugs that mention influxdb somewhere.

**Comment by andyxning** [comment]
I can help to do some job in this but must be after Spring Festival. Too busy for now.

**Comment by acobaugh** [comment]
I can likely help with this. May take me a little bit to learn the code, but most of the bugs look pretty straight forward. Was going to work on #1579 (was actually going to file that bug and one about allowing the RP to be selected instead of using `default` always when I saw the bug already existed).

**Comment by DirectXMan12** [comment]
sounds good.  I'll cc you on a couple of issues for triage just so you can get a feel for it, and then if you're up for it we'll add you to the sink owners documentation.

**Comment by devopsprosiva** [comment]
@acobaugh Any idea when the update for selecting `rp` will be available?

**Comment by acobaugh** [comment]
I wanted to run a quick test of my code in #1959.

**Comment by DirectXMan12** [comment]
I'm going to close this now, since @acobaugh is in the Influx owners file.
