### ISSUE TITLE
A huge number of tag values causes influxdb to take up very high memory

### ISSUE THREAD

**Issue by stanxing** [kubernetes/heapster#1948]
- I used  influxdb as sink to store metrics in k8s. The specific retention policy in influxdb is 90 days. The beginning is smooth, but as time goes by, influxdb's memory usage gets higher and higher.So when I looked for the source of the problem , I found heapster wrote a lot of tag keys into influxdb.
![2018-02-01 16-02-53](https://user-images.githubusercontent.com/23288646/35667665-83f159f4-0769-11e8-8f96-9aa9d92f179f.png)
-  I think it is normal behavior, except `pod_name`, `container_base_image`, `pod_id`(had removed in heapster v1.5.0). Because the values of `pod_name` and `container_base_image` are random and unexpected. they should not be used as a tag  but rather as a field. With each pod deployment, it will produce a lot of the corresponding tag values and the value is unlimited. So the tag set get bigger and bigger. I think  the value of  a tag key should be a limited collection. 
- I want to know this design using `pod_name` and ` container_base_image` as a tag is out of what kind of consideration?

**Comment by acobaugh** [comment]
This is likely more of an influxdb problem than a heapster problem per se. On your influxdb system `influx -execute 'show series on k8s'  | wc -l`. Memory consumption is roughly a function of series cardinality. When you approach 1M series, the older inmem index format starts to show its limitations: https://www.influxdata.com/blog/path-1-billion-time-series-influxdb-high-cardinality-indexing-ready-testing/

This could also be caused by inadequate shard group duration tuning. I think in general you want the shard duration to be short enough that the indexes don't grow to be huge (>~5GB in size).

I do wonder if we need to add options to omit certain tags, particularly the ones that are always going to be changing. So leave out at least pod_name and pod_id, and instead rely on labels in our queries.

**Comment by acobaugh** [comment]
After some casual observation of my own cluster with hardly anything running in it, I have 2613 series over 36 measurements. 34 of those measurements have `/` in the name, and they all seem to have a single field named `value`. If we collapsed the measurements with `/` in them into a single measurement by using multiple fields per measurement (ie, all memory values in a single measurement called `memory`), then we should be able to reduce cardinality by almost an order of magnitude. We may also be able to do away with the `*_rate` measurements, because we can get that with the derivative() influxql  function.

**Comment by stanxing** [comment]
@acobaugh 
- I have considered the possibility of setting pod_name as field key ,but I found it hid a bigger problem.If `pod_name` is a filed key,  it will not have a unique tag key (pod_id have be moved in heapster v1.5) to identify the point data and cause the data written to be overwritten. For example, influxdb wrote data in the timestamp (1519455048000000): "cpu/request namespace=default, value=100 pod_name=k8s-nginx-f278" and the next point data was also written in the same timestamp (1519455048000000): "cpu/request namespace=default, value=100 pod_name=k8s-nginx-1234", it will overwrite the previous point data. So `pod_name` is not be used as field key.
- Also, field key should be a metric in influxdb( it is my understanding), just like `request`, `limit` as field key in cpu measurement, so it not suitable for influxdb to regard `pod_name` as a field key.
- May be the method you said that collapsed the measurements with / in them into a single measurement is a better way to reduce the usage of memory. According to my test ,  memory was reduced by 40%, (series reduced from 158696 to 45101). But I read the article(https://www.influxdata.com/blog/path-1-billion-time-series-influxdb-high-cardinality-indexing-ready-testing/) and found maybe the best way is TSI index based disk space. As you said , this is likely more of an influxdb problem than a heapster problem per se.
