### ISSUE TITLE
Grafana do not have cluster and pods dashboards 

### ISSUE THREAD

**Issue by Itfly** [kubernetes/heapster#2013]
**Description**
I setup Heapster, InfluxDB and Grafana within the[ influxdb doc](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md), just download the kube-config files at this commit: `ad3b64845fa9b2211062ba48d80cd84a46c72419`
I just modify two things:

- adding env name: INFLUXDB_BIND_ADDRESS and value: "127.0.0.1:8088" for localhost lookup problem.
- use NodePort in grafana

After login-in Grafana UI within admin/admin, there's nothing shown (no config, no dashboard).

However, i can manually add the influxDB and[ cluster/pods dashboard](https://github.com/kubernetes/heapster/tree/master/grafana/dashboards).

Is this normal?

**Output of `heapster --version`:**

```
k8s.gcr.io/heapster-amd64:v1.4.2
 k8s.gcr.io/heapster-grafana-amd64:v4.4.3
```

**Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}


```

**Comment by ttarczynski** [comment]
I've also seen a very similar issue with newer grafana image: `gcr.io/google_containers/heapster-grafana-amd64:v5.0.4`
* grafana starts properly
* there are no Pods and Clusters dashboards
* Importing the [cluster.json](https://github.com/kubernetes/heapster/blob/master/grafana/dashboards/cluster.json) results with and empty dashboard (without any panels or graphs)
* I've managed to get importing work  by applying this patch: #1796 (which was reverted this year with commit [b67384](https://github.com/kubernetes/heapster/commit/b6738402e7ec00547e85662147c51ace77d0be7d#diff-86c2a8bf96397cbe9f7d6fe70031f313))


I've also found in grafana logs what happens when the `setup_grafana` script posts these 2 dashboards:
* both requests end with HTTP 422 responses:
```
t=2018-09-06T10:48:52+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/dashboards/db status=422 remote_addr=[::1] time_ms=71 size=84 referer=
t=2018-09-06T10:48:52+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/dashboards/db status=422 remote_addr=[::1] time_ms=4 size=84 referer=
```

**Comment by lixianyang** [comment]
@ttarczynski I have the same problem

t=2018-09-10T15:57:05+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
Connected to the Grafana dashboard.
The datasource for the Grafana dashboard is now set.
t=2018-09-10T15:57:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/dashboards/db status=422 remote_addr=[::1] time_ms=4 size=84 referer=
t=2018-09-10T15:57:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/dashboards/db status=422 remote_addr=[::1] time_ms=4 size=84 referer=

**Comment by lixianyang** [comment]
Use heapster-grafana-amd64:v4.4.3 can show dashboard
