### ISSUE TITLE
Add support for Grafana v2.0

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#249]

**Comment by vishh** [comment]
cc @saad-ali

**Comment by thucatebay** [comment]
@vishh Please let me know what else needs to be done here. Perhaps I can help.

**Comment by eliaslevy** [comment]
This is still broken on the `beta.gcr.io/google_containers/heapster_grafana:v2.1.1` container.  Attempting to use the Grafana UI through the apiserver proxy results in 404s when Grafana trying to find the CSS and JS files.  Commenting out the GF_SERVER_ROOT_URL env variable in the Pod spec allows the CS and JS to load, but then it can't load dashboards, as the XHR requests no longer have the proxy path prepended to their path. Is seems there is a disconnect between the apiserver proxy and Grafana as to whether the proxied requests will have the proxy path prepended on them or not, which is leading Grafana not to find its files when processing the request.

**Comment by eliaslevy** [comment]
Grafana is correctly making use of the GF_SERVER_STATIC_ROOT_PATH config env variable to to prepend the proxy path to the link, base, and script elements, but the apiserver proxy is rewriting the HTML to insert the path as well.  Thus, you end up with a duplicate path that messes up Grafana.  

If you don't use GF_SERVER_STATIC_ROOT_PATH, then the static assets load fine, but the XHR requests fail, as now they don't know the correct URL to use for requests. 

I am guessing the solution to this is to change the apiserver proxy so that it checks the URLs its trying to rewrite to determine if they already have the proxy path prepended to them, and if so, skip rewriting them.  Otherwise, Grafana won't run in proxy mode.

**Comment by vishh** [comment]
The proxy on the apiserver has been causing quite some trouble. Thanks for digging in. Will you be able to post a patch to fix this?

**Comment by eliaslevy** [comment]
I'll see what I can do tomorrow.

**Comment by eliaslevy** [comment]
As of k8s v.1.1.1 Grafana 2.1.0 is working.  Looks like @vishh fixed the double prefix issue in kubernetes/kubernetes@2a075cd4bd04a003045d4946065b4cf153803446, which made it into v1.1.1.  I think this issue can be closed.  Thanks @vishh.
