### ISSUE TITLE
Switch to a docker based build

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#474]
The current build system is not cross OS compatible. Switching over to a docker based build system will be helpful in the long run.

**Comment by afein** [comment]
As of Docker 1.8 we can use docker cp to copy files outside of a container.

Because of that, we can build a heapster-build container based on the golang image and copy the heapster binary outside of the container when the build is finished.

Then, we can normally build the alpine-based image using the existing dockerfile, which will copy the new binary into the final container image.

**Comment by vishh** [comment]
@afein: Wanna give it a shot? ;)

**Comment by afein** [comment]
sure, expect a PR within the week

**Comment by piosz** [comment]
closing in favor of #1056
