### ISSUE TITLE
Support access to historical data via the model APIs 

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#481]
Currently, heapster stores a day's worth of data in memory, as part of the model. The data stored in memory can be lossy (less precision to save memory). Heapster needs to provide access to historical data as well. 
Some initial use cases for this data are:
1. Initial Resource Recommendations for Containers and Pods - this can be based on several parameters like docker image name, labels, etc. 
2. Visualizing historical data.
3. Predicting future usage of containers, pods and nodes.
4. Avoid losing cached in-memory data upon restart
The existing APIs can be extended to support historical data. If the requested duration is beyond what is stored in the in-memory cache (model), we can query the user configured sink for historical data.
Specifically,
1. Sinks should provide a read interface
2. Model, or a layer above it, should translate the API queries into Read operations on the Sink and provide appropriate response.
3. Upon restart, if a sink was configured, heapster should retrieve historical stats for the last day, for all currently running pods and containers, and warm up the in-memory model.

**Comment by a-robinson** [comment]
I hope you don't mind me playing devil's advocate -- why is storing historical data heapster's job? Isn't that the point of the sinks?

I do see a lot of value in being able to read historical data in a backend-agnostic way, but I have two thoughts on that:

1. We should be careful to avoid trying to do too much. Scope how many different kinds of data munging and aggregation we're willing to do. Limit the number of backends we support unless others are willing to own them.

1. Be careful about how much memory we use while plumbing through historical data. It'd actually make some sense for this to be a separate component, such that the reading of metrics couldn't interfere with the ingestion of metrics.

This honestly seems like the sort of thing that might eventually benefit from being a separate project rather than tied to kubernetes, but that's definitely too much extra work for now.

**Comment by vishh** [comment]
The intention is to abstract storage backends. The backends can be InfluxDB, or hawkular or GCM. 
The maintenance overhead is a valid concern. As of now the intention is to only support a few required backends (as mentioned above). The scope is limited to kubernetes metrics data required for various components like horizontal auto scaler, initial limits controller, scheduler, etc.
Having small microservices makes sense on the outset, but it also adds deployment and maintenance overhead. Since heapster is the one that controls the storage schema, having heapster read back the data makes it easy to guarantee API semantics. To avoid the query resource consumption issues, we can consider adding resource constraints per-query. Thanks for bringing this up. The design for the Sink read interface should try to minimize memory overhead.

**Comment by vishh** [comment]
One more points: The initial use cases demand access to usage histograms only. We can expand the scope to raw historical metrics if required in the future.

**Comment by vishh** [comment]
cc @piosz @mwielgus

**Comment by fgrzadkowski** [comment]
We don't want to do this right now. We might come back to this later.
