### ISSUE TITLE
Set error margin on Day Store

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#486]
Day Store internally uses Stats Store which provides a rolling window bucket based storage model. To improve memory utilization, we can set error margins  (eplison) for individual compute resources. Each resource belonging to a container is mapped to a Stat Store. 
Here are some sample epsilon values:
1. Cpu - 50 milli cores 
2. Memory - 4 MBytes
3. Disk - 10MBytes
4. Network - 10KBytes
5. Disk I/O - ?? 

cc @afein

**Comment by vishh** [comment]
#478

**Comment by afein** [comment]
As of now, limits are being treated as metrics and they are, therefore, stored in a DayStore
I propose that, initially, we should utilize the same epsilon for usages and limits.
Then, after the current set of P0 issues is completed, we can edit the model to handle limits as constants, rather than timeseries.

**Comment by vishh** [comment]
Can you open a separate issue for handling limits?

**Comment by afein** [comment]
Opened limits handling as #493

**Comment by vishh** [comment]
@afein: Has this issue been resolved?

**Comment by afein** [comment]
Yes, static epsilon configuration was resolved as part of #508.
More dynamic options could be explored for future milestones, if that is deemed useful.

**Comment by vishh** [comment]
Thanks @afein. Feel free to file an issue if you have some thoughts on
dynamic epsilon config.
