### ISSUE TITLE
Network metrics always shows 0 bytes

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/heapster#500]
Hello,
The network/tx and network/rx always shows 0 bytes in the graph.

Thanks,
Shilpa

**Comment by jimmidyson** [comment]
@shilpapadgaonkar This is a bug in cadvisor which kubernetes embeds - fixed in latest cadvisor yesterday, will try to get kubernetes godeps bumped today. See https://github.com/google/cadvisor/issues/822 & https://github.com/google/cadvisor/pull/865. This is due to a previous incompatibility with cadvisor & docker >= 1.7 when libnetwork was introduced.
