### ISSUE TITLE
Failed to store events in cache

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#544]
UID is somehow empty.

```
kube_events.go:127] failed to store events in cache: failed to store event {{pulled default   kubernetes-minion-46ao map[]  2015-09-14 11:23:56 +0000 UTC} Container image "heapster:e2e_test" already present on machine kubelet {{ } {heapster-2cfng.1403d442280a5e66  default /api/v1/namespaces/default/events/heapster-2cfng.1403d442280a5e66  1359241 0 0001-01-01 00:00:00 +0000 UTC 2015-09-14 12:23:56 +0000 UTC map[] map[]} {Pod default heapster-2cfng bcc1b6b4-5ad2-11e5-9eee-42010af0996d v1 1359054 spec.containers{heapster}} pulled Container image "heapster:e2e_test" already present on machine {kubelet kubernetes-minion-46ao} 2015-09-14 11:21:26 +0000 UTC 2015-09-14 11:23:56 +0000 UTC 2}} - UID cannot be empty
```

**Comment by vishh** [comment]
Looks like events do not have UID set. Switching to using names which are unique.

**Comment by mwielgus** [comment]
Shouldn't we rather fix it in Kubernetes?

**Comment by mwielgus** [comment]
Actually events do have UID set. I generated the similar event and it looks OK. The above is not also lacking UID but also creationTimestamp - I would suggest dropping broken events or giving them heapster generated uid - if uid & creation time is broken why should we assume that the name is fine?

```json
        {
            "kind": "Event",
            "apiVersion": "v1",
            "metadata": {
                "name": "cassandra.1404cab927c4af5f",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/events/cassandra.1404cab927c4af5f",
                "uid": "b014a366-5d49-11e5-bdca-42010af07fef",
                "resourceVersion": "120398",
                "creationTimestamp": "2015-09-17T14:37:57Z",
                "deletionTimestamp": "2015-09-17T15:37:57Z"
            },
            "involvedObject": {
                "kind": "Pod",
                "namespace": "default",
                "name": "cassandra",
                "uid": "b00af05b-5d49-11e5-bdca-42010af07fef",
                "apiVersion": "v1",
                "resourceVersion": "120395",
                "fieldPath": "implicitly required container POD"
            },
            "reason": "pulled",
            "message": "Container image \"gcr.io/google_containers/pause:0.8.0\" already present on machine",
            "source": {
                "component": "kubelet",
                "host": "kubernetes-minion-knk4"
            },
            "firstTimestamp": "2015-09-17T14:37:57Z",
            "lastTimestamp": "2015-09-17T14:37:57Z",
            "count": 1
        },
```

**Comment by vishh** [comment]
[Here](
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/record/event.go#L273)
is the relevant code. Kubernetes uses event Name to identify events.
Arguably this can be fixed. But until it is fixed, heapster needs to work
around that. Timestamps are not an issue since if it is not present, it
does not affect heapster. It might confuse users though. So it has to be
fixed in Kubernetes side as well.

Generating UIDs in heapster is not possible since heapster is stateless. If
heapster were to retrieve the same event after a restart, it will assign
different UIDs. We can use a hash as a UID possibly.

The main use case of UIDs is to avoid duplicates while storing in sinks and
in core heapster logic. Since these requirements are met by event.Name for
now, I chose to go with that. WDYT?

**Comment by mwielgus** [comment]
Do you know who is assigning the uids and how it could fail?

**Comment by vishh** [comment]
More details on this issue:
https://github.com/kubernetes/kubernetes/issues/14126
