### ISSUE TITLE
Do not export Kube specific model endpoints in non-kube clusters

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#575]
@afein: Can we avoid exposing endpoints specific to kubernetes clusters like `namespaces` and `pods` from non-kubernetes clusters? AFAIK, the other endpoints like containers, nodes and cluster should still continue to work.

**Comment by afein** [comment]
That is certainly possible. We would have to create a "Kubernetes mode" on the model which would cause the Kubernetes-specific API endpoints to return an appropriate message instead of invoking their corresponding Getter methods. 

Other than that, no further changes should be needed, as no PodElements should be received by the cache in non-Kubernetes clusters.

**Comment by vishh** [comment]
Instead of returning an error, I am suggesting not exposing the
Kubernetes-specific endpoints at all - basically not registering those
endpoints. WDYT?

**Comment by afein** [comment]
That would be also possible by editing the API handlers to skip endpoint registration according to a certain flag.

This behavior could be also automated by attempting to access kube-dns from within heapster, instead of asking for a CLI flag.

**Comment by mwielgus** [comment]
+1, I can do it on Monday. Kube-dns is not (or at least was not) obligatory so I would rather stick to the flag.

**Comment by vishh** [comment]
+1 for flag based control.
