### ISSUE TITLE
heapster:v0.18.1 not compatible with Influx 0.9x and Grafana 2.x

### ISSUE THREAD

**Issue by lachlanbull** [kubernetes/heapster#625]
Someone recently pushed an update with kubernetes/heapster_grafana:v2.1.0 and kubernetes/heapster_influxdb:v0.5 which is causing problems on Kubernetes clusters.

Basically the heapster container can no longer create the database because 0.9x has a significantly different API. Using kubernetes/heapster_influxdb:v0.4 fixes the issue but causes errors with default Grafana dashboards.
Dashboard init failed
Template variables could not be initialized: InfluxDB Error: <br/>syntax error, unexpected SIMPLE_NAME SHOW TAG VALUES FROM "uptime_ms_cumulative" WITH KEY = "hostname"	^^^^

Heapster Error:
I1002 06:22:24.025855       1 heapster.go:55] /heapster --source=kubernetes:https://10.124.116.1 --sink=influxdb:http://10.124.118.218:8086
I1002 06:22:24.025922       1 heapster.go:56] Heapster version 0.18.1
I1002 06:22:24.026283       1 kube_factory.go:169] Using Kubernetes client with master "https://10.124.116.1" and version "v1"
I1002 06:22:24.026293       1 kube_factory.go:170] Using kubelet port 10255
E1002 06:22:24.029215       1 driver.go:326] Database creation failed: Server returned (404): 404 page not found
. Retrying after 30 seconds
E1002 06:22:54.030607       1 driver.go:326] Database creation failed: Server returned (404): 404 page not found
. Retrying after 30 seconds
E1002 06:23:24.031977       1 driver.go:326] Database creation failed: Server returned (404): 404 page not found
. Retrying after 30 seconds

**Comment by vishh** [comment]
We recommend to use the heapster configs bundled with specific kubernetes releases. We would ideally like heapster HEAD to support all kubernetes releases, but with the current velocity of changes, that is proving to be difficult. 

If you can provide me your kube and heapster versions along with pointers to deployment files you are using for heapster, I can suggest modifications.

**Comment by lachlanbull** [comment]
Hi Vishh,
I had been using heapster from the kubernetes releases, i think around release 1.05 it broke. I'm reasonably sure it's the same issues.

I've been using a relatively straight forward AWS build from the included /cluster/aws scripts.
Currently on Release 1.0.6, grafana 2.1 starts but never configures a data source.

**Comment by ecnahc515** [comment]
@lachlanbull I can also confirm the same. Works on v1.0.4 but not after.

**Comment by vishh** [comment]
@lachlanbull: I have tried setting up an influxdb data source in `proxy` mode with `http://localhost:8086` as the URL. Is that what you tried setting up? 

The title of this issue says that v0.18.1 is not compatible with InfluxDB v0.9. I believe this issue is because the deployment scripts on HEAD are tied to past releases. I'm working on nightly builds that should resolve this issue.

**Comment by lachlanbull** [comment]
Hi Vish, 
Appreciate you checking, Yes so i manually specified the service address endpoint but it's same behaviour as using localhost in a single node setup. 

Later today i'll try manually building the docker images to see if i can get it working.

**Comment by vishh** [comment]
I'm updating the scripts on HEAD to use a `canary` tagged image that will include support for InfluxDB v0.9.
Grafana will no longer be accessible using apiserver proxy. The default service file sets up a LoadBalancer. If that doesn't work for you, I will be happy to help.
My interpretation of this issue is essentially HEAD configs being incompatible with each other.

**Comment by lachlanbull** [comment]
"Grafana will no longer be accessible using apiserver proxy" - Yeah fair enough, I've been advertising the routes for service range from VPC so i can reach them easily enough without the ELB.

I'll let you know how it goes.

**Comment by andrewmichaelsmith** [comment]
I've just loaded `cluster/addons/cluster-monitoring/influxdb`. When I go to: `:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/datasources` Grafana loads but I get the

```InfluxDB` Error: <br/>404 page not found error.```

I read what you said about LoadBalancers - I just set a nodePort on my `grafana-service.yaml` but when I go to :nodePort Grafana doesn't even load because all the HTML is referencing `/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/css/`.

Did I miss something here?

**Comment by vishh** [comment]
InfluxDB v0.9 is supported from v0.19+

**Comment by andrewmichaelsmith** [comment]
So is the problem that the yml files define [heapster v0.20](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml#L29) and [influxdb 0.5](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml#L23)?

**Comment by vishh** [comment]
That configuration is expected to work

**Comment by andrewmichaelsmith** [comment]
With that configuration I get the 404 error above.

Fairly sure I'm on the right images:

```
$ kubectl --namespace=kube-system get rc | grep -e heap -e minto
heapster-v14                     heapster                      gcr.io/google_containers/heapster:v0.20.0-alpha7             k8s-app=heapster,version=v14                     1          19h
                                 eventer                       gcr.io/google_containers/heapster:v0.20.0-alpha7                                                              
monitoring-influxdb-grafana-v3   influxdb                      gcr.io/google_containers/heapster_influxdb:v0.5              k8s-app=influxGrafana,version=v3                 1         19h
                                 grafana                       gcr.io/google_containers/heapster_grafana:v2.1.1                                                              
```

**Comment by vishh** [comment]
Have you updated the grafana configs to work with NodePorts or
LoadBalancer? Look in the configs, there will be comments on how to make it
work outside of the proxy.
