### ISSUE TITLE
Test Hawkular sink

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#933]
Please take a look the Hawkular sink and check if everything is in order there. You may want to implement LabeledMetrics support.

**Comment by mwielgus** [comment]
ref: #910

**Comment by jimmidyson** [comment]
@mwringe Can you look at the Hawkular sink please & add support for LabeledMetrics as required? Thanks!

**Comment by mwringe** [comment]
@jimmidyson ok

**Comment by jimmidyson** [comment]
Thanks!

**Comment by piosz** [comment]
Any progress?

**Comment by mwringe** [comment]
Sorry, I have been busy with some other stuff, and wow, I can't believe its been so long since I was looking at this. I should hopefully have time to get back to this in the next couple of days.

I had it partially working with the Hawkular sink, but the lack of differentiation labels on LabeledMetrics meant that they could not be properly categorized and stored. I think I had to add the host labels and then it was working correctly, but I would have to go back and check what I exactly I had working.

**Comment by piosz** [comment]
@mwringe @jimmidyson Is Hawkular sink working correctly? If yes let's close this.

**Comment by mwringe** [comment]
@piosz I think we can close this, we have labeledMetric support

**Comment by piosz** [comment]
Thanks for the update.
